name: Data Fetching
on: 
  push:
      branches-ignore:
        - alpha
  schedule:
    - cron: "5 19 * * *"
  workflow_dispatch:

jobs:
  Fetch-Route-Data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
            architecture: 'x64'
            cache: 'pip'
            cache-dependency-path: crawling/requirements.txt
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r ./crawling/requirements.txt
      - name: Crawling resources
        shell: bash
        env:
          REQUEST_LIMIT: "6"
        run: |
          set -o xtrace
          python ./crawling/parseHoliday.py
          python ./crawling/ctb.py
          python ./crawling/kmb.py
          python ./crawling/nlb.py
          python ./crawling/lrtfeeder.py
          python ./crawling/lightRail.py
          python ./crawling/mtr.py
          python ./crawling/parseJourneyTime.py
          python ./crawling/parseGtfs.py
          python ./crawling/parseGtfsEn.py
          python ./crawling/gmb.py
          python ./crawling/sunferry.py
          python ./crawling/fortuneferry.py
          python ./crawling/hkkf.py
          python ./crawling/matchGtfs.py
          python ./crawling/cleansing.py
          python ./crawling/mergeRoutes.py
          python ./crawling/mergeStopList.py
          python ./crawling/routeCompare.py
          python ./crawling/mtrExits.py

      - name: Update MD5
        shell: bash
        run: |
          md5sum routeFareList.min.json | cut -f1 -d ' ' | tr -d $'\n' > routeFareList.md5
          md5sum routeFareList.alpha.min.json | cut -f1 -d ' ' | tr -d $'\n' > routeFareList.alpha.md5

      - name: Archive crawling outputs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Crawled Files
          retention-days: 14
          path: |
            holiday.json
            routeFareList*
            routeList*
            stopList*
            stopMap*
            routeTime.json
            gtfs
            gtfs.json
            routeGtfs*
            gtfs.zip
            ROUTE_BUS.xml
            route-ts/
            exits.mtr.json
      - name: create deployment folder
        shell: bash
        run: mkdir -p build
      - name: cp files into deployment folder
        shell: bash
        run: |
          cp \
          routeFareList.json \
          routeFareList.min.json \
          routeFareList.alpha.json \
          routeFareList.alpha.min.json \
          routeFareList.md5 \
          routeFareList.alpha.md5  \
          CNAME \
          exits.mtr.json \
          build/
      - name: cp route-ts into deployment folder
        run: cp -r route-ts build
      - name: Update resources
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            folder: build
            commit-message: Update resources
            branch: gh-pages
            clean: false
            clean-exclude: |
              alpha/*

      - name: Check if alpha branch status
        id: alpha-check
        shell: bash
        run: |
          ALPHA_BRANCH_NAME=alpha
          echo "alpha_exist=$( git rev-parse --verify --no-revs "${ALPHA_BRANCH_NAME}" && echo yes )" >> "$GITHUB_OUTPUT"
          # Basically, this command will do the diff
          # > git diff --exit-code --no-patch <base>...<test_branch>
          echo "alpha_newer=$( git diff --exit-code --no-patch master..."${ALPHA_BRANCH_NAME}" > /dev/null || echo yes )" >> "$GITHUB_OUTPUT"

      - name: Copy master build to alpha when no update or not exist
        if: github.ref_name == 'master' && ( steps.alpha-check.outputs.alpha_newer != 'yes' || steps.alpha-check.outputs.alpha_exist != 'yes')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            target-folder: alpha/
            folder: build
            commit-message: Update resources
            branch: gh-pages
            clean: false
            clean-exclude: |
              alpha/*
      
      # FIXME: Implement the logic on alpha is newer
